# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Basic site settings ###################################################

title: Vipul Sharma
email: sharma.vips5512@gmail.com
author: Vipul Sharma
description: >- # this means ignore newlines
        Being a Devops Engineer most of my time goes into LINUX ( the soul of Devops ), 
        Also i like to explore tools from development perspective and extend their functionality. 

baseurl: ""
url: "https://vipssharma.github.io/"

# Jekyll settings #######################################################

# this tells jekyll to include the content of the _pages
# folder when generating the static site
include:
  - _pages

# options for SASS (compiled CSS)
sass:
  # source folder
  sass_dir: _sass
  # when compiling, minimize size
  style: compressed

### ! these cannot be changed for Github pages ! ###

# index for related posts
lsi: false
# disable custom plugins
safe: true
# markdown conversion
markdown: kramdown
# highlighting for text and code
highlighter: rouge
# build only pages that changed
incremental: false

### ! these can be changed ! ###

# show excerpts from posts on the news page
show_excerpts: true

# Jekyll plugins go here
plugins:
  # generate a <head> tag for SEO automatically
  - jekyll-seo-tag
  # generates an rss feed from posts and news
  - jekyll-feed
  
# Custom settings #######################################################

# social/analytics variables
logo: "/assets/images/me.jpg"
linkedin_username: vipul0sharma
github_username:  VipsSharma

# Nav
navigation:
  - item: "About"
    link: "/about/"
  - item: "Resume"
    link: "/CV.pdf"
  - item: "Thoughts"
    link: "/posts/"
